{{- if and .Values.gitea.enabled .Values.gitea.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: gitea
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubezero-lib.labels" $ | nindent 4 }}
spec:
  gateways:
  - {{ .Values.gitea.istio.gateway }}
  hosts:
  - {{ .Values.gitea.istio.url }}
  http:
  - match:
    - headers:
        user-agent:
          regex: '(?i).*(?:AI2Bot|AddSearchBot|Ai2Bot-Dolma|Amazonbot|Andibot|Anomura|Applebot|Applebot-Extended|Awario|Bravebot|Brightbot 1\.0|Bytespider|CCBot|ChatGPT Agent|ChatGPT-User|Claude-SearchBot|Claude-User|Claude-Web|ClaudeBot|CloudVertexBot|Cloudflare-AutoRAG|Cotoyogi|Crawlspace|Datenbank Crawler|DeepSeekBot|Devin|Diffbot|DuckAssistBot|Echobot Bot|EchoboxBot|FacebookBot|Factset_spyderbot|FirecrawlAgent|FriendlyCrawler|GPTBot|Gemini-Deep-Research|Google-CloudVertexBot|Google-Extended|Google-Firebase|Google-NotebookLM|GoogleAgent-Mariner|GoogleOther|GoogleOther-Image|GoogleOther-Video|ICC-Crawler|ISSCyberRiskCrawler|IbouBot|ImagesiftBot|Kangaroo Bot|LinerBot|Meta-ExternalAgent|Meta-ExternalFetcher|MistralAI-User|MistralAI-User/1\.0|MyCentralAIScraperBot|NovaAct|OAI-SearchBot|OpenAI|Operator|PanguBot|Panscient|Perplexity-User|PerplexityBot|PetalBot|PhindBot|Poseidon Research Crawler|QualifiedBot|QuillBot|SBIntuitionsBot|Scrapy).*'
    - headers:
        user-agent:
          regex: '(?i).*(?:SemrushBot-OCOB|SemrushBot-SWA|ShapBot|Sidetrade indexer bot|TerraCotta|Thinkbot|TikTokSpider|Timpibot|VelenPublicWebCrawler|WARDBot|Webzio-Extended|YaK|YandexAdditional|YandexAdditionalBot|YouBot|aiHitBot|amazon-kendra-|anthropic-ai|bedrockbot|bigsur\.ai|cohere-ai|cohere-training-data-crawler|facebookexternalhit|iaskspider/2\.0|img2dataset|meta-externalagent|meta-externalfetcher|meta-webindexer|netEstate Imprint Crawler|omgili|omgilibot|panscient\.com|quillbot\.com|wpbot).*'
    directResponse:
      status: 418
  - match:
    - uri:
        exact: /assets/img/logo.svg
    - uri:
        exact: /assets/img/favicon.svg
    redirect:
      authority: cdn.zero-downtime.net
      uri: /assets/zdt/logo.svg
  - match:
    - uri:
        exact: /assets/img/favicon.png
    redirect:
      authority: cdn.zero-downtime.net
      uri: /assets/zdt/logo-small-64.png
  - name: api
    match:
    - uri:
       prefix: /api/
    route:
    - destination:
        host: gitea-http
  - name: notApi
    route:
    - destination:
        host: gitea-http
  tcp:
  - match:
    - port: 22
    route:
    - destination:
        host: gitea-ssh
{{- end }}
