apiVersion: v2
description: KubeZero Argo - Events, Workflow, CD
name: kubezero-argo
version: 0.3.3
home: https://kubezero.com
icon: https://cdn.zero-downtime.net/assets/kubezero/logo-small-64.png
keywords:
  - kubezero
  - argocd
  - argo-events
  - argo-workflow
maintainers:
  - name: Stefan Reimer
    email: stefan@zero-downtime.net
# Url: https://github.com/argoproj/argo-helm/tree/main/charts
dependencies:
  - name: kubezero-lib
    version: 0.2.1
    repository: https://cdn.zero-downtime.net/charts/
  - name: argo-events
    version: 2.4.15
    repository: https://argoproj.github.io/argo-helm
    condition: argo-events.enabled
  - name: argo-cd
    version: 7.9.0
    repository: https://argoproj.github.io/argo-helm
    condition: argo-cd.enabled
  - name: argocd-image-updater
    version: 0.12.1
    repository: https://argoproj.github.io/argo-helm
    condition: argocd-image-updater.enabled
kubeVersion: ">= 1.30.0-0"
