{{- if .Values.PersistentVolume }}
{{- if .Values.PersistentVolume.create }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ default "kubezero-efs-pv" .Values.PersistentVolume.Name }}
  labels:
{{ include "kubezero-lib.labels" . | indent 4 }}
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.PersistentVolume.EfsId }}
{{- end }}
{{- end }}
