apiVersion: v2
name: kubezero-istio
description: KubeZero Umbrella Chart for Istio
type: application
version: 0.0.1
appVersion: 1.5
home: https://kubezero.com
icon: https://cdn.zero-downtime.net/assets/kubezero/logo-small-64.png
keywords:
  - kubezero
  - istio
maintainers:
  - name: Quarky9
dependencies:
  - name: kubezero-lib
    version: ">= 0.1.1"
    repository: https://zero-down-time.github.io/kubezero/
  - name: istio-operator
    version: "= 1.5"
kubeVersion: ">= 1.16.0"
