apiVersion: v2
name: kubezero-istio
description: KubeZero Umbrella Chart for Istio
type: application
version: 0.26.2
home: https://kubezero.com
icon: https://cdn.zero-downtime.net/assets/kubezero/logo-small-64.png
keywords:
  - kubezero
  - istio
maintainers:
  - name: Stefan Reimer
    email: stefan@zero-downtime.net
dependencies:
  - name: kubezero-lib
    version: 0.2.1
    repository: https://cdn.zero-downtime.net/charts/
  - name: envoy-ratelimit
    version: 0.1.2
    repository: https://cdn.zero-downtime.net/charts/
    condition: envoy-ratelimit.enabled
  - name: base
    version: 1.26.3
    repository: https://istio-release.storage.googleapis.com/charts
  - name: istiod
    version: 1.26.3
    repository: https://istio-release.storage.googleapis.com/charts
  - name: kiali-server
    version: "2.13.0"
    repository: https://kiali.org/helm-charts
    condition: kiali-server.enabled
kubeVersion: ">= 1.30.0-0"
