global:
  variant: distroless

  logAsJson: true

  nativeNftables: true
  networkPolicy:
    enabled: true
  defaultPodDisruptionBudget:
    enabled: false

  # tag: 1.28.4


istiod:
  autoscaleEnabled: false
  replicaCount: 1

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 256Mi

# env:
#   PILOT_ENABLE_MYSQL_FILTER: true
#   PILOT_ENABLE_REDIS_FILTER: true
#   PILOT_HTTP10: true

  telemetry:
    enabled: false
    # install our dashboards via gzip pipeline
    dashboards: false

  meshConfig:
    accessLogFile: /dev/stdout
    accessLogEncoding: 'JSON'
    accessLogFormat: |
      {
        "start_time": "%START_TIME%",
        "method": "%REQ(:METHOD)%",
        "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
        "protocol": "%PROTOCOL%",
        "response_code": "%RESPONSE_CODE%",
        "response_flags": "%RESPONSE_FLAGS%",
        "response_code_details": "%RESPONSE_CODE_DETAILS%",
        "connection_termination_details": "%CONNECTION_TERMINATION_DETAILS%",
        "upstream_transport_failure_reason": "%UPSTREAM_TRANSPORT_FAILURE_REASON%",
        "bytes_received": "%BYTES_RECEIVED%",
        "bytes_sent": "%BYTES_SENT%",
        "duration": "%DURATION%",
        "upstream_service_time": "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%",
        "x_forwarded_for": "%REQ(X-FORWARDED-FOR)%",
        "user_agent": "%REQ(USER-AGENT)%",
        "request_id": "%REQ(X-REQUEST-ID)%",
        "authority": "%REQ(:AUTHORITY)%",
        "upstream_host": "%UPSTREAM_HOST%",
        "upstream_cluster": "%UPSTREAM_CLUSTER%",
        "upstream_local_address": "%UPSTREAM_LOCAL_ADDRESS%",
        "downstream_local_address": "%DOWNSTREAM_LOCAL_ADDRESS%",
        "downstream_remote_address": "%DOWNSTREAM_REMOTE_ADDRESS%",
        "requested_server_name": "%REQUESTED_SERVER_NAME%",
        "route_name": "%ROUTE_NAME%",
        "log_type": "accessLog",
        "connection_id": "%CONNECTION_ID%",
        "ja4": "%TLS_JA4_FINGERPRINT%"
      }

    tcpKeepalive:
      interval: 60s
      time: 120s

kiali-server:
  enabled: false

  auth:
    strategy: anonymous

  deployment:
    ingress_enabled: false
    view_only_mode: true

  server:
    metrics_enabled: false

  external_services:
    custom_dashboards:
      enabled: false

    prometheus:
      url: "http://metrics-kube-prometheus-st-prometheus.monitoring:9090"

  istio:
    enabled: false
    gateway: istio-ingress/private-ingressgateway
    #url: "kiali.example.com"


# for available options see envoy-ratelimit chart
envoy-ratelimit:
  enabled: false
