apiVersion: v2
name: kubezero
description: KubeZero - Root App of Apps chart
type: application
version: 1.32.5
home: https://kubezero.com
icon: https://cdn.zero-downtime.net/assets/kubezero/logo-small-64.png
keywords:
  - kubezero
  - argocd
maintainers:
  - name: Stefan Reimer
    email: stefan@zero-downtime.net
dependencies:
  - name: kubezero-lib
    version: 0.2.1
    repository: https://cdn.zero-downtime.net/charts
kubeVersion: ">= 1.32.0-0"
