apiVersion: v2
name: kubezero-logging
description: KubeZero Umbrella Chart for complete EFK stack
type: application
version: 0.3.7
appVersion: 1.2.1
home: https://kubezero.com
icon: https://cdn.zero-downtime.net/assets/kubezero/logo-small-64.png
keywords:
  - kubezero
  - elasticsearch
  - kibana
  - fluentd
  - fluent-bit
maintainers:
  - name: Quarky9
dependencies:
  - name: kubezero-lib
    version: ">= 0.1.3"
    repository: https://zero-down-time.github.io/kubezero/
  - name: fluentd
    version: 2.5.1
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: fluentd.enabled
  - name: fluent-bit
    version: 0.7.2
    repository: https://zero-down-time.github.io/kubezero/
    # repository: https://fluent.github.io/helm-charts
    condition: fluent-bit.enabled
kubeVersion: ">= 1.16.0"
