{
 "title": "OpenEBS / Replicated PV / Mayastor / DiskPool",
 "tags": [
  "OpenEBS",
  "Mayastor"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "mayastor_diskpool",
    "query": {
     "query": "label_values(diskpool_status,name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "DiskPool Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "diskpool_status{name=~\"$mayastor_diskpool\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "DiskPool Total Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "diskpool_total_size_bytes{name=~\"$mayastor_diskpool\"}/(1024*1024*1024)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "DiskPool Used Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "diskpool_used_size_bytes{name=~\"$mayastor_diskpool\"}/(1024*1024*1024)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "DiskPool Available Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "(diskpool_total_size_bytes{name=~\"$mayastor_diskpool\"}-diskpool_used_size_bytes{name=~\"$mayastor_diskpool\"})/(1024*1024*1024)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(diskpool_num_read_ops{name=~\"$mayastor_diskpool\"}[1m])",
     "legendFormat": "read iops"
    },
    {
     "expr": "irate(diskpool_num_write_ops{name=~\"$mayastor_diskpool\"}[1m])",
     "legendFormat": "write iops"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(diskpool_bytes_read{name=~\"$mayastor_diskpool\"}[1m])",
     "legendFormat": "read"
    },
    {
     "expr": "irate(diskpool_bytes_written{name=~\"$mayastor_diskpool\"}[1m])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "((irate(diskpool_read_latency_us{name=~\"$mayastor_diskpool\"}[1m]))/(irate(diskpool_num_read_ops{name=~\"$mayastor_diskpool\"}[1m])))/1000000",
     "legendFormat": "read"
    },
    {
     "expr": "((irate(diskpool_write_latency_us{name=~\"$mayastor_diskpool\"}[1m]))/(irate(diskpool_num_write_ops{name=~\"$mayastor_diskpool\"}[1m])))/1000000",
     "legendFormat": "write"
    }
   ]
  }
 ]
}