{
 "title": "OpenEBS / Replicated PV / Mayastor / Volume",
 "tags": [
  "OpenEBS",
  "Mayastor"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "pv_name",
    "query": {
     "query": "label_values(volume_num_read_ops,pv_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(volume_num_read_ops{pv_name=~\"$pv_name\"}[1m])",
     "legendFormat": "read"
    },
    {
     "expr": "irate(volume_num_write_ops{pv_name=~\"$pv_name\"}[1m])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(volume_bytes_read{pv_name=~\"$pv_name\"}[1m])",
     "legendFormat": "read"
    },
    {
     "expr": "irate(volume_bytes_written{pv_name=~\"$pv_name\"}[1m])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "((irate(volume_read_latency_us{pv_name=~\"$pv_name\"}[1m]))/(irate(volume_num_read_ops{pv_name=~\"$pv_name\"}[1m])))/1000000",
     "legendFormat": "read"
    },
    {
     "expr": "((irate(volume_write_latency_us{pv_name=~\"$pv_name\"}[1m]))/(irate(volume_num_write_ops{pv_name=~\"$pv_name\"}[1m])))/1000000",
     "legendFormat": "write"
    }
   ]
  }
 ]
}