{{- if .Values.bestPractices.enabled }}
apiVersion: policies.kyverno.io/v1
kind: MutatingPolicy
metadata:
  name: rename-bitnami2legacy
  annotations:
    policies.kyverno.io/title: Rename all Bitnami images to legacy
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/minversion: 1.18.0
    policies.kyverno.io/description: >-
      Replaces all docker image URLs from bitnami to bitnamilegacy.
      This is stop gap solution to deal with the Broadcom / Bitnami changes
      in September 2025.
spec:
  evaluation:
    background:
      enabled: false
  autogen:
    podControllers:
      controllers:
        - none
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        operations:
          - CREATE
          - UPDATE
  variables:
    - name: prefix
      expression: '"docker.io/bitnami/"'
    - name: legacy
      expression: '"docker.io/bitnamilegacy/"'
  mutations:
    - patchType: ApplyConfiguration
      applyConfiguration:
        expression: >-
          Object{
            spec: Object.spec{
              containers: object.spec.containers.map(c, Object.spec.containers{
                name: c.name,
                image: c.image.startsWith(variables.prefix)
                  ? variables.legacy + c.image.substring(size(variables.prefix))
                  : c.image
              }),
              initContainers: (has(object.spec.initContainers) ? object.spec.initContainers : []).map(c, Object.spec.initContainers{
                name: c.name,
                image: c.image.startsWith(variables.prefix)
                  ? variables.legacy + c.image.substring(size(variables.prefix))
                  : c.image
              }),
              ephemeralContainers: (has(object.spec.ephemeralContainers) ? object.spec.ephemeralContainers : []).map(c, Object.spec.ephemeralContainers{
                name: c.name,
                image: c.image.startsWith(variables.prefix)
                  ? variables.legacy + c.image.substring(size(variables.prefix))
                  : c.image
              })
            }
          }
{{- end }}
