apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubezero-lib.labels" . | nindent 4 }}
data:
  ingress.yaml: |
    domain: ingress
    descriptors:
    {{- toYaml .Values.descriptors.ingress | nindent 4 }}

  private-ingress.yaml: |
    domain: private-ingress
    descriptors:
    {{- toYaml .Values.descriptors.privateIngress | nindent 4 }}
