apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratelimit-redis
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratelimit-redis
  template:
    metadata:
      labels:
        app: ratelimit-redis
    spec:
      containers:
      - image: redis:6-alpine
        imagePullPolicy: IfNotPresent
        name: redis
        ports:
        - name: redis
          containerPort: 6379
      restartPolicy: Always
      serviceAccountName: ""
