{{- if and .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-rate-limiting
  labels:
    {{- include "kubezero-lib.labels" . | nindent 4 }}
spec:
  jobLabel: istio
  targetLabels: [app]
  selector:
    matchExpressions:
    - {key: app, operator: In, values: [ratelimit]}
  endpoints:
  - port: http-monitoring
---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-rate-limiting-redis
  labels:
    {{- include "kubezero-lib.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: ratelimit-redis
      redis_setup_type: standalone
  endpoints:
  - port: redis-exporter
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
{{- end }}
