apiVersion: v1
kind: Service
metadata:
  name: ratelimit
  namespace: {{ .Release.Namespace }}
  labels:
    app: ratelimit
spec:
  ports:
  #- name: http-port
  #  port: 8080
  #  targetPort: 8080
  #  protocol: TCP
  - name: grpc-port
    port: 8081
    targetPort: 8081
    protocol: TCP
  #- name: http-debug
  #  port: 6070
  #  targetPort: 6070
  #  protocol: TCP
  - name: http-monitoring
    port: 9102
    targetPort: 9102
    protocol: TCP
  selector:
    app: ratelimit
