apiVersion: v1
kind: Service
metadata:
  name: ratelimit-valkey
  namespace: {{ .Release.Namespace }}
  labels:
    app: ratelimit-valkey
spec:
  ports:
  - name: valkey
    port: 6379
  selector:
    app: ratelimit-valkey
