apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratelimit-valkey
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratelimit-valkey
  template:
    metadata:
      labels:
        app: ratelimit-valkey
    spec:
      containers:
      - image: valkey/valkey:8.1-alpine3.21
        imagePullPolicy: IfNotPresent
        name: valkey
        ports:
        - name: valkey
          containerPort: 6379
      restartPolicy: Always
      serviceAccountName: ""
