rules:
- name: rabbitmq-cluster-alarms
  condition: 'and ( index .Values "rabbitmq-cluster-operator" "enabled" ) ( index .Values "rabbitmq-cluster-operator" "dashboards" )'
  url: https://raw.githubusercontent.com/rabbitmq/cluster-operator/refs/heads/main/observability/prometheus/rule-file.yml
