{{- if .Values.kibana.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "kubezero-lib.fullname" . }}-kibana
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "kubezero-lib.labels" . | indent 4 }} 
spec:
  hosts:
  - {{ .Values.kibana.istio.url }}
  gateways:
  - {{ default "istio-system/ingressgateway" .Values.kibana.istio.gateway }}
  http:
  - route:
    - destination:
        host: {{ template "kubezero-lib.fullname" . }}-kb-http
{{- end }}
