apiVersion: v2
name: kubezero-app
description: KubeZero ArgoCD Application - Root chart of the KubeZero
type: application
version: 0.2.0
home: https://kubezero.com
icon: https://cdn.zero-downtime.net/assets/logo_small.png
keywords:
  - kubezero
  - argocd
  - gitops
maintainers:
  - name: Quarky9
kubeVersion: ">= 1.16.0"
