apiVersion: v2
name: kubezero-app
description: KubeZero ArgoCD Application - Root chart of the KubeZero
type: application
version: 0.2.1
home: https://kubezero.com
icon: https://cdn.zero-downtime.net/assets/logo_small.png
keywords:
  - kubezero
  - argocd
  - gitops
maintainers:
  - name: Quarky9
dependencies:
  - name: kubezero-lib
    version: ">= 0.1.1"
    repository: https://zero-down-time.github.io/kubezero/
kubeVersion: ">= 1.16.0"
