ClusterName: Test-cluster
Domain: example.com

platform: aws
HighAvailableControlplane: false

calico:
  enabled: true

cert-manager:
  enabled: true
  IamArn: ""

aws-ebs-csi-driver:
  enabled: true
  IamArn: ""

aws-efs-csi-driver:
  enabled: false

kiam:
  enabled: true
  IamArn: ""

istio:
  enabled: false

prometheus:
  enabled: false

argo-cd:
  server: {}
  istio:
    enabled: true
    gateway: private-ingressgateway.istio-system.svc.cluster.local
