apiVersion: v2
name: kubeadm
description: KubeZero Kubeadm cluster config
type: application
version: 1.33.5
home: https://kubezero.com
icon: https://cdn.zero-downtime.net/assets/kubezero/logo-small-64.png
keywords:
  - kubezero
  - kubeadm
maintainers:
  - name: Stefan Reimer
    email: stefan@zero-downtime.net
kubeVersion: ">= 1.33.0-0"
