{{- if index .Values "cert-manager" "enabled" }}
{{ template "kubezero.app" dict "root" . "name" "cert-manager" "type" "helm" }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  annotations:
    iam.amazonaws.com/permitted: ".*CertManagerRole.*"
{{- end }}
