apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubezero
  namespace: argocd
  labels:
    app.kubernetes.io/name: kubezero
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  project: kubezero
  source:
    repoURL: https://github.com/Zero-Down-Time/kubezero
    targetRevision: HEAD
    path: charts/kubezero-app

    helm:
      values: |
{{- toYaml .Values.kubezero | nindent 8 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
