{{- if .Values.calico.enabled }}
{{ include "kubezero-app.app" . }}

  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /status
{{- end }}
