{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argocd-server
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-argocd-virtualservice
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: server
spec:
  gateways:
  - {{ .Values.istio.gateway }}
  hosts:
  - {{ index .Values "argo-cd" "server" "config" "url" }}
  http:
  - name: grpc
    match:
    - headers:
        user-agent:
          prefix: argocd-client
    route:
    - destination:
        host: {{ .Release.Name }}-argocd-server
        port:
          number: 443
  - name: http
    route:
    - destination:
        host: {{ .Release.Name }}-argocd-server
        port:
          number: 80
{{- end }}
