{{- define "network-values" }}
cilium:
  k8sServiceHost: {{ .Values.global.apiServerUrl }}

# {{- if eq .Values.global.platform "aws" }}
# image:
#   pullPolicy: Never
# {{- end }}
# k8s:
#   apiServerURLs: "https://{{ .Values.global.apiServerUrl }}"

  cluster:
    name: {{ .Values.global.clusterName }}
  {{- with ((.Values.network.cilium).cluster).id }}
  ipam:
    operator:
      clusterPoolIPv4PodCIDRList:
        - 10.{{ . }}.0.0/16
  {{- end }}

  prometheus:
    enabled: {{ .Values.metrics.enabled }}
    serviceMonitor:
      enabled: {{ .Values.metrics.enabled }}

  operator:
    {{- if .Values.global.highAvailable }}
    replicas: 2
    {{- end }}
    prometheus:
      enabled: {{ .Values.metrics.enabled }}
      serviceMonitor:
        enabled: {{ .Values.metrics.enabled }}

{{- with .Values.network.haproxy }}
haproxy:
  {{- toYaml . | nindent 2 }}
{{- end }}

{{- end }}


{{- define "network-argo" }}
  # Metallb
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /spec/conversion/webhook/clientConfig/caBundle
{{- end }}

{{ include "kubezero-app.app" . }}
