{{- define "telemetry-values" }}

metrics:
  enabled: {{ .Values.metrics.enabled }}

{{- if index .Values "telemetry" "fluent-bit" }}
fluent-bit:
  {{- with index .Values.telemetry "fluent-bit" }}
  {{- toYaml . | nindent 2 }}
  {{- end }}

  serviceMonitor:
    enabled: {{ .Values.metrics.enabled }}
{{- end }}

{{- if .Values.telemetry.fluentd }}
fluentd:
  {{- with .Values.telemetry.fluentd }}
  {{- toYaml . | nindent 2 }}
  {{- end }}

  metrics:
    serviceMonitor:
      enabled: {{ .Values.metrics.enabled }}
{{- end }}

{{- if index .Values "telemetry" "data-prepper" }}
data-prepper:
  {{- with index .Values "telemetry" "data-prepper" }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}

{{- if index .Values "telemetry" "opentelemetry-collector" }}
opentelemetry-collector:
  {{- with index .Values "telemetry" "opentelemetry-collector" }}
  {{- toYaml . | nindent 2 }}
  {{- end }}

  serviceMonitor:
    enabled: {{ .Values.metrics.enabled }}
{{- end }}

{{- if .Values.telemetry.jaeger }}
jaeger:
  {{- with .Values.telemetry.jaeger }}
  {{- toYaml . | nindent 2 }}
  {{- end }}

  collector:
    serviceMonitor:
      enabled: {{ .Values.metrics.enabled }}
  query:
    serviceMonitor:
      enabled: {{ .Values.metrics.enabled }}
{{- end }}

{{- if .Values.telemetry.opensearch }}
opensearch:
  {{- with .Values.telemetry.opensearch }}
  {{- toYaml . | nindent 2 }}
  {{- end }}

# Disabled until upstream made up their mind
# https://github.com/opensearch-project/technical-steering/issues/35
# serviceMonitor:
#   enabled: {{ .Values.metrics.enabled }}
{{- end }}

{{- if index .Values "telemetry" "opensearch-dashboards" }}
opensearch-dashboards:
  {{- with index .Values "telemetry" "opensearch-dashboards" }}
  {{- toYaml . | nindent 2 }}
  {{- end }}

# Disabled until upstream made up their mind
# https://github.com/opensearch-project/technical-steering/issues/35
# serviceMonitor:
#   enabled: {{ .Values.metrics.enabled }}
{{- end }}

{{- end }}


{{- define "telemetry-argo" }}

{{- end }}

{{ include "kubezero-app.app" . }}
