apiVersion: v2
name: kubezero-sql
description: KubeZero umbrella chart for SQL databases, mariadb-galera
type: application
version: 0.4.0
home: https://kubezero.com
icon: https://cdn.zero-downtime.net/assets/kubezero/logo-small-64.png
keywords:
  - kubezero
  - mariadb
  - galera
maintainers:
  - name: Stefan Reimer
    email: stefan@zero-downtime.net
dependencies:
  - name: kubezero-lib
    version: ">= 0.1.6"
    repository: https://cdn.zero-downtime.net/charts/
  - name: mariadb-galera
    version: 14.0.10
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb-galera.enabled
kubeVersion: ">= 1.26.0"
