mariadb-galera:
  enabled: false

  replicaCount: 2

  db:
    user: mariadb

  # For a single node "cluster" force bootstrap
  #galera:
    #bootstrap:
    #  bootstrapFromNode: 0
    #  forceSafeToBootstrap: true

  metrics:
    enabled: false
    # set to false for any subsequent installation of the chart in the same cluster to prevent overwriting each other
    installDashboard: true
    serviceMonitor:
      enabled: false

    prometheusRules:
      enabled: false

  istio:
    enabled: false
    gateway: istio-ingress/private-ingressgateway
    url: mariadb.example.com

  configurationConfigMap: "{{ .Release.Name }}-mariadb-galera-configuration"
