apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elastic-operator
spec:
  template:
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
