{{- if .Values.rabbitmq.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.rabbitmq.name }}
  labels:
    {{ include "kubezero-lib.labels" . | nindent 4 }}
spec:
  gateways:
  - {{ .Values.rabbitmq.istio.gateway }}
  hosts:
  - {{ index .Values "rabbitmq" "istio" "url" }}
  http:
  - route:
    - destination:
        host: {{ .Values.rabbitmq.name }}
        port:
          number: 15672
  {{- if or .Values.rabbitmq.istio.amqp .Values.rabbitmq.istio.amqps .Values.rabbitmq.istio.mqtt .Values.rabbitmq.istio.mqtts }}
  tcp:
  {{- if .Values.rabbitmq.istio.amqps }}
  - match:
    - port: 5671
    route:
    - destination:
        host: {{ .Values.rabbitmq.name }}
        port:
          number: 5672
  {{- end }}
  {{- if .Values.rabbitmq.istio.amqp }}
  - match:
    - port: 5672
    route:
    - destination:
        host: {{ .Values.rabbitmq.name }}
        port:
          number: 5672
  {{- end }}
  {{- if .Values.rabbitmq.istio.mqtts }}
  - match:
    - port: 8883
    route:
    - destination:
        host: {{ .Values.rabbitmq.name }}
        port:
          number: 1883
  {{- end }}
  {{- if .Values.rabbitmq.istio.mqtt }}
  - match:
    - port: 1883
    route:
    - destination:
        host: {{ .Values.rabbitmq.name }}
        port:
          number: 1883
  {{- end }}
  {{- end }}
{{- end }}
