spec:
  template:
    spec:
      containers:
      - name: coredns
        resources:
          requests:
            cpu: 100m
            memory: 32Mi
          limits:
            memory: 128Mi
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
