spec:
  dnsPolicy: ClusterFirstWithHostNet
  containers:
  - name: kube-apiserver
    resources:
      requests:
        cpu: 200m
        memory: 1536Mi
      limits:
        memory: 3Gi
    env:
    env:
    - name: GOMAXPROCS
      value: "1"
    - name: GOMEMLIMIT
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
