{{- if .Values.fluentd.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "kubezero-lib.fullname" $ }}-fluentd-secret
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "kubezero-lib.labels" . | indent 4 }}
data:
  shared_key: {{ .Values.fluentd.shared_key | b64enc | quote }}
{{- end }}
