#!/usr/bin/env bash
#
# sync-osd-dashboards.sh
#   Pulls AWS "Centralized Logging with OpenSearch" (CLO) index templates and
#   saved-object dashboards for each configured service, substitutes the
#   `%%INDEX%%` placeholder, gzip+base64-encodes the assets, and writes one
#   Helm ConfigMap manifest per service under templates/OSDashboards/.
#
#   The runtime install Job (templates/OSDashboards/install-job.yaml) mounts
#   the ConfigMaps, decompresses on the pod, and applies the templates +
#   dashboards via the OpenSearch and OpenSearch Dashboards APIs.
#
# Re-run after CLO upstream changes to refresh the embedded assets.
#
# Usage:
#   scipts/sync-osd-dashboards.sh                 # use built-in service list
#   scipts/sync-osd-dashboards.sh foo bar=baz     # override service list
#
#   Each entry is `name` or `name=source`. `name` is the local service name —
#   the value substituted for %%INDEX%% (so it shows in index pattern and
#   dashboard titles), the index-template name, and the ConfigMap/output-file
#   name. Use only k8s-safe chars (lowercase, digits, hyphens) — no underscores.
#   `source` is the CLO upstream filename to fetch (defaults to `name`); use it
#   when our name differs from CLO's, e.g. `s3-access-logs=s3`.
#
# Source:
#   https://github.com/aws-solutions/centralized-logging-with-opensearch
#   .../source/constructs/lambda/pipeline/log-processor/assets/
#       index_template/<source>.json
#       saved_objects/<source>.ndjson
#
set -euo pipefail

REPO=${REPO:-aws-solutions/centralized-logging-with-opensearch}
REF=${REF:-main}
BASE="https://raw.githubusercontent.com/${REPO}/${REF}/source/constructs/lambda/pipeline/log-processor/assets"

# Resolve chart root relative to this script so it works from any cwd.
ROOT="$(cd -- "$(dirname -- "$0")"/.. >/dev/null && pwd)"
OUT="$ROOT/templates/OSDashboards"
mkdir -p "$OUT"

# Default service list. Entries are `name` or `name=source` (see header).
default_services=(cloudfront cloudtrail s3-access-logs=s3 lambda)
services=("${@:-${default_services[@]}}")

# Portable base64 (Linux/macOS), no line wraps.
b64() { base64 | tr -d '\n'; }

# Fetch one URL into stdout; abort with a clear message on HTTP failure.
fetch() {
  local url=$1
  curl -sSfL "$url" \
    || { echo "ERROR: fetch failed: $url" >&2; exit 1; }
}

for entry in "${services[@]}"; do
  svc="${entry%%=*}"   # local name: %%INDEX%% value, index-template + CM name
  src="${entry##*=}"   # CLO upstream filename to fetch (defaults to svc)
  echo ">>> $svc (CLO source: $src)"

  tmpl=$(fetch "$BASE/index_template/$src.json")
  ndjs=$(fetch "$BASE/saved_objects/$src.ndjson")

  # Patch known CLO upstream typos: a stray char appended directly after the
  # %%INDEX%% placeholder at the end of a saved-object id/string (e.g. the s3
  # dashboard's `panel_1` reference is `...-%%INDEX%%f`, leaving a dangling
  # "Could not locate that visualization" panel). No-op for clean files.
  ndjs=$(printf '%s' "$ndjs" | sed 's/%%INDEX%%[A-Za-z]*"/%%INDEX%%"/g')

  # CLO's lambda index-pattern title is a bare `%%INDEX%%` (no wildcard), so it
  # would match only an index literally named <svc>, not the dated <svc>-* ones
  # our sink writes. Make the index-pattern title a wildcard. No-op for services
  # whose title already carries `-*` (the char after %%INDEX%% there is `-`).
  ndjs=$(printf '%s' "$ndjs" | sed 's/"title":"%%INDEX%%"/"title":"%%INDEX%%-*"/g')

  tmpl=$(printf '%s' "$tmpl" | sed "s/%%INDEX%%/$svc/g")
  ndjs=$(printf '%s' "$ndjs" | sed "s/%%INDEX%%/$svc/g")

  # CLO ships bare {aliases,mappings,settings} index bodies; wrap them into a
  # composable _index_template body so the install Job can PUT them directly.
  tmpl=$(printf '{"index_patterns":["%s-*"],"priority":100,"template":%s}' \
                "$svc" "$tmpl")

  tmpl_b64=$(printf '%s' "$tmpl" | gzip -9c | b64)
  ndjs_b64=$(printf '%s' "$ndjs" | gzip -9c | b64)

  out="$OUT/$svc.yaml"
  cat > "$out" <<EOF
{{- if .Values.osdashboards.enabled }}
# Auto-generated by scipts/sync-osd-dashboards.sh — do not hand-edit.
# Source: https://github.com/${REPO}/tree/${REF}/source/constructs/lambda/pipeline/log-processor/assets
# Service: ${svc} (CLO source: ${src})    Index placeholder: %%INDEX%% -> ${svc}
apiVersion: v1
kind: ConfigMap
metadata:
  name: osdashboards-${svc}
  labels:
    app.kubernetes.io/name: osdashboards
    app.kubernetes.io/component: ${svc}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
binaryData:
  index_template.json.gz: ${tmpl_b64}
  dashboard.ndjson.gz: ${ndjs_b64}
{{- end }}
EOF
  printf '    wrote %s (%d bytes)\n' "$out" "$(wc -c <"$out")"
done

echo "Done. ${#services[@]} service(s) synced."
