apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: {{ include "gatewayName" . | trimPrefix "istio-" }}-listener
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "kubezero-lib.labels" . | nindent 4 }}
spec:
  workloadSelector:
    labels:
      {{- include "gatewaySelectorLabels" . | nindent 6 }}
  configPatches:
  - applyTo: LISTENER_FILTER
    match:
      context: GATEWAY
      listener:
        portNumber: 8443
        listenerFilter: "envoy.filters.listener.tls_inspector"
    patch:
      operation: REPLACE
      value:
         name: envoy.filters.listener.tls_inspector
         typed_config:
           "@type": type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
           "initialReadBufferSize": 512
         filter_disabled:
           destination_port_range:
             start: 1025
             end: 1026
