prometheus-operator:
  alertmanager:
    enabled: false
  coreDns:
    enabled: false
  kubeApiServer:
    enabled: false
  kubeControllerManager:
    enabled: false
  kubeDns:
    enabled: false
  kubeEtcd:
    enabled: false
  kubeProxy:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeStateMetrics:
    enabled: false
  kubelet:
    enabled: false
  nodeExporter:
    enabled: false
  grafana:
    enabled: false
  prometheus:
    enabled: false
  defaultRules:
    create: false

  prometheusOperator:
    enabled: true
    image:
      tag: v0.41.0

    # Run on controller nodes
    tolerations:
    - key: node-role.kubernetes.io/master
      effect: NoSchedule
    nodeSelector:
      node-role.kubernetes.io/master: ""

    # Argo takes care of CRDs
    manageCrds: false
    createCustomResource: true

    # Operator has TLS support starting 0.39, but chart does not support CAConfig and operator flags yet
    # see: https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/webhook.md#deploying-the-admission-webhook
    # Until then we disable them as the patching interferes with Argo anyways
    tlsProxy:
      enabled: false
    admissionWebhooks:
      enabled: false

    #namespaces:
    #  releaseNamespace: true
    #  additional:
    #    - kube-system
