prometheus-operator:
  alertmanager:
    enabled: false
  coreDns:
    enabled: false
  kubeApiServer:
    enabled: false
  kubeControllerManager:
    enabled: false
  kubeDns:
    enabled: false
  kubeEtcd:
    enabled: false
  kubeProxy:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeStateMetrics:
    enabled: false
  kubelet:
    enabled: false
  nodeExporter:
    enabled: false
  grafana:
    enabled: false
  prometheus:
    enabled: false
  defaultRules:
    create: false
  # Default configuration of prometheus operator will create CRDs in the cluster idempotently
  prometheusOperator:
    enabled: true

    # Run on controller nodes
    tolerations:
    - key: node-role.kubernetes.io/master
      effect: NoSchedule
    nodeSelector:
      node-role.kubernetes.io/master: ""

    # We use Argo
    manageCrds: false
    createCustomResource: true

    # Operator has TLS support starting 0.39, but chart does not support CAConfig and operator flags yet
    # see: https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/webhook.md#deploying-the-admission-webhook
    # Until then we use the patch job and tls proxy, to be reviewed later on to use the kubezero local cluster CA from cert-manager
    tlsProxy:
      enabled: true
    admissionWebhooks:
      enabled: true
      patch:
        enabled: true
        tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
        nodeSelector:
          node-role.kubernetes.io/master: ""

    #namespaces:
    #  releaseNamespace: true
    #  additional:
    #    - kube-system
