apiVersion: v1
kind: Secret
metadata:
  name: neo4j-admin
  labels:
    {{- include "kubezero-lib.labels" . | nindent 4 }}
type: Opaque
data:
  NEO4J_AUTH: {{.Values.neo4j.neo4j.password | printf "neo4j/%v" | b64enc -}}
