apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubezero
  namespace: argocd
  labels:
{{ include "kubezero-lib.labels" . | indent 4 }}
spec:
  project: kubezero
  source:
    repoURL: {{ .Values.kubezero.global.defaultSource.repoURL }}
    targetRevision: {{ .Values.kubezero.global.defaultSource.targetRevision }}
    path: {{ .Values.kubezero.global.defaultSource.pathPrefix}}charts/kubezero

    helm:
      values: |
        {{- toYaml .Values.kubezero | nindent 8 }}

  destination:
    server: {{ .Values.kubezero.global.defaultDestination.server }}
    namespace: argocd

  {{- if .Values.kubezero.global.syncPolicy }}
  syncPolicy:
    {{- toYaml .Values.kubezero.global.syncPolicy | nindent 4 }}
  {{- end }}
