keycloak:
  enabled: false

  production: true
  hostnameStrict: true
  proxyHeaders: xforwarded

  auth:
    adminUser: admin
    existingSecret: kubezero-auth
    passwordSecretKey: admin-password

  replicaCount: 1

  pdb:
    create: false
    minAvailable: 1

  resources:
    limits:
      #cpu: 750m
      memory: 768Mi
    requests:
      cpu: 100m
      memory: 512Mi

  metrics:
    enabled: false
    serviceMonitor:
      enabled: true

  postgresql:
    auth:
      existingSecret: kubezero-auth
      username: keycloak
      database: keycloak

    primary:
      persistence:
        size: 1Gi

    readReplicas:
      replicaCount: 0

  istio:
    admin:
      enabled: false
      gateway: istio-ingress/private-ingressgateway
      url: ""
    auth:
      enabled: false
      gateway: istio-ingress/ingressgateway
      url: ""
