keycloak:
  enabled: false

  production: true
  hostnameStrict: false
  proxyHeaders: xforwarded

  auth:
    adminUser: admin
    existingSecret: keycloak-auth
    passwordSecretKey: admin-password

  replicaCount: 1

  pdb:
    create: false
    minAvailable: 1

  resources:
    limits:
      #cpu: 750m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi

  metrics:
    enabled: false
    serviceMonitor:
      enabled: true

  externalDatabase:
    host: "keycloak-pg-rw"
    port: 5432
    user: keycloak
    database: keycloak
    existingSecret: keycloak-pg
    existingSecretPasswordKey: "password"

  postgresql:
    enabled: false

  istio:
    admin:
      enabled: false
      gateway: istio-ingress/private-ingressgateway
      url: ""
    auth:
      enabled: false
      gateway: istio-ingress/ingressgateway
      url: ""
