keycloakx:
  enabled: false

  command:
    - "/opt/keycloak/bin/kc.sh"
    - "--verbose"
    - "start"
    - "--http-port=8080"
    - "--spi-events-listener-jboss-logging-success-level=info"
    - "--spi-events-listener-jboss-logging-error-level=warn"

  http:
    relativePath: "/"

  database:
    vendor: postgres
    hostname: "keycloak-pg-rw"
    port: 5432
    database: keycloak
    username: keycloak
    existingSecret: keycloak-pg
    existingSecretKey: password

  resources:
    limits:
      #cpu: 750m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 640Mi

  podDisruptionBudget: {}
  #  maxUnavailable: 1
  #  minAvailable: 1

  metrics:
    enabled: false
  serviceMonitor:
    enabled: false
    interval: 30s

  service:
    httpPort: 8080

  proxy:
    mode: xforwarded

  istio:
    admin:
      enabled: false
      gateway: istio-ingress/private-ingressgateway
      url: ""
    auth:
      enabled: false
      gateway: istio-ingress/ingressgateway
      url: ""
