---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubezero-lib.fullname" . }}
  labels:
    {{- include "kubezero-lib.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.plausible.replicaCount }}
  selector:
    matchLabels:
      {{- include "kubezero-lib.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.plausible.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kubezero-lib.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.plausible.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.plausible.podSecurityContext | nindent 8 }}
      volumes:
        {{- if .Values.plausible.databaseCA }}
        - name: database-ca
          secret:
            secretName: {{ include "kubezero-lib.secretName" . }}
            items:
              - key: DATABASE_CA
                path: database-ca.pem
        {{- end }}
        {{- with .Values.plausible.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.plausible.securityContext | nindent 12 }}
          image: "{{ .Values.plausible.image.repository }}:{{ .Values.plausible.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.plausible.image.pullPolicy }}
          command:
            - /bin/sh
            - -x
            - -c
            - /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run
          volumeMounts:
            {{- if .Values.plausible.databaseCA }}
            - name: database-ca
              mountPath: /etc/ssl/certs/plausible/
              readOnly: true
            {{- end }}
            {{- with .Values.plausible.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            {{- if .Values.plausible.baseURL }}
            - name: BASE_URL
              value: {{ .Values.plausible.baseURL | toString | quote }}
            {{- end }}
            {{- if .Values.plausible.listenip }}
            - name: LISTEN_IP
              value: {{ .Values.plausible.listenip | toString | quote }}
            {{- end }}
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  key: SECRET_KEY_BASE
                  name: {{ include "kubezero-lib.fullname" . }}
            - name: TOTP_VAULT_KEY
              valueFrom:
                secretKeyRef:
                  key: TOTP_VAULT_KEY
                  name: {{ include "kubezero-lib.fullname" . }}
            {{- if .Values.plausible.disableRegistration }}
            - name: DISABLE_REGISTRATION
              value: {{ .Values.plausible.disableRegistration | toString | quote }}
            {{- end }}
            {{- if .Values.plausible.logFailedLoginAttempts }}
            - name: LOG_FAILED_LOGIN_ATTEMPTS
              value: {{ .Values.plausible.logFailedLoginAttempts | toString | quote }}
            {{- end }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: DATABASE_URL
                  name: {{ include "kubezero-lib.fullname" . }}
            {{- if .Values.plausible.databaseCA }}
            - name: DATABASE_CACERTFILE
              value: /etc/ssl/certs/plausible/database-ca.pem
            {{- end }}
            - name: CLICKHOUSE_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: CLICKHOUSE_DATABASE_URL
                  name: {{ include "kubezero-lib.fullname" . }}
            {{- if .Values.plausible.mailer.enabled }}
            {{- if .Values.plausible.mailer.email }}
            - name: MAILER_EMAIL
              value: {{ .Values.plausible.mailer.email | toString | quote }}
            {{- end }}
            {{- if .Values.plausible.mailer.adapter }}
            - name: MAILER_ADAPTER
              value: {{ .Values.plausible.mailer.adapter | toString | quote }}
            {{- end }}
            {{- if eq .Values.plausible.mailer.adapter "Bamboo.Mua" }}
            {{- if .Values.plausible.mailer.smtp.host }}
            - name: SMTP_HOST_ADDR
              value: {{ .Values.plausible.mailer.smtp.host | toString | quote }}
            {{- end }}
            {{- if .Values.plausible.mailer.smtp.port }}
            - name: SMTP_HOST_PORT
              value: {{ .Values.plausible.mailer.smtp.port | toString | quote }}
            {{- end }}
            {{- if .Values.plausible.mailer.smtp.auth }}
            {{- if .Values.plausible.mailer.smtp.username }}
            - name: SMTP_USER_NAME
              value: {{ .Values.plausible.mailer.smtp.username | toString | quote }}
            {{- end }}
            - name: SMTP_USER_PWD
              valueFrom:
                secretKeyRef:
                  key: SMTP_USER_PWD
                  name: {{ include "kubezero-lib.fullname" . }}
            {{- end }}
            {{- if .Values.plausible.mailer.smtp.ssl }}
            - name: SMTP_HOST_SSL_ENABLED
              value: {{ .Values.plausible.mailer.smtp.ssl | toString | quote }}
            {{- end }}
            {{- if .Values.plausible.mailer.smtp.retries }}
            - name: SMTP_RETRIES
              value: {{ .Values.plausible.mailer.smtp.retries | toString | quote }}
            {{- end }}
            {{- end }}
            {{- if eq .Values.plausible.mailer.adapter "Bamboo.PostmarkAdapter" }}
            - name: POSTMARK_API_KEY
              valueFrom:
                secretKeyRef:
                  key: POSTMARK_API_KEY
                  name: {{ include "kubezero-lib.fullname" . }}
            {{- end }}
            {{- if eq .Values.plausible.mailer.adapter "Bamboo.MailgunAdapter" }}
            - name: MAILGUN_API_KEY
              valueFrom:
                secretKeyRef:
                  key: MAILGUN_API_KEY
                  name: {{ include "kubezero-lib.fullname" . }}
            {{- if .Values.plausible.mailer.mailgun.domain }}
            - name: MAILGUN_DOMAIN
              value: {{ .Values.plausible.mailer.mailgun.domain | toString | quote }}
            {{- end }}
            {{- if .Values.plausible.mailer.mailgun.baseURI }}
            - name: MAILGUN_BASE_URI
              value: {{ .Values.plausible.mailer.mailgun.baseURI | toString | quote }}
            {{- end }}
            {{- end }}
            {{- if eq .Values.plausible.mailer.adapter "Bamboo.MandrillAdapter" }}
            - name: MANDRILL_API_KEY
              valueFrom:
                secretKeyRef:
                  key: MANDRILL_API_KEY
                  name: {{ include "kubezero-lib.fullname" . }}
            {{- end }}
            {{- if eq .Values.plausible.mailer.adapter "Bamboo.SendGridAdapter" }}
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  key: SENDGRID_API_KEY
                  name: {{ include "kubezero-lib.fullname" . }}
            {{- end }}
            {{- end }}
            {{- if .Values.plausible.extra_geolocation.enabled }}
            - name: MAXMIND_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  key: MAXMIND_LICENSE_KEY
                  name: {{ include "kubezero-lib.fullname" . }}
            {{- if .Values.plausible.extra_geolocation.maxmind.edition }}
            - name: MAXMIND_EDITION
              value: {{ .Values.plausible.extra_geolocation.maxmind.edition | toString | quote }}
            {{- end }}
            {{- if .Values.plausible.extra_geolocation.geolite2CountryDB }}
            - name: GEOLITE2_COUNTRY_DB
              value: {{ .Values.plausible.extra_geolocation.geolite2CountryDB | toString | quote }}
            {{- end }}
            {{- if .Values.plausible.extra_geolocation.geolite2CountryDB }}
            - name: GEONAMES_SOURCE_FILE
              value: {{ .Values.plausible.extra_geolocation.geonamesSourceFile | toString | quote }}
            {{- end }}
            {{- end }}
            {{- if .Values.plausible.google.enabled }}
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: GOOGLE_CLIENT_ID
                  name: {{ include "kubezero-lib.fullname" . }}
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: GOOGLE_CLIENT_SECRET
                  name: {{ include "kubezero-lib.fullname" . }}
            {{- end }}
            {{- if .Values.plausible.extraEnv }}
            {{- toYaml .Values.plausible.extraEnv | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.plausible.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.plausible.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.plausible.resources | nindent 12 }}
      {{- with .Values.plausible.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.plausible.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.plausible.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
