{{- if .Values.plausible.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubezero-lib.fullname" . }}
  labels:
    app: plausible
  {{- include "kubezero-lib.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.plausible.secretKeyBase }}
  SECRET_KEY_BASE: {{ .Values.plausible.secretKeyBase | toString | b64enc }}
  {{- else }}
  SECRET_KEY_BASE: {{ randAlphaNum 90 | toString | b64enc }}
  {{- end }}
  TOTP_VAULT_KEY: {{ .Values.plausible.totpVaultKey | toString | b64enc }}
  {{- if .Values.plausible.databaseURL }}
  DATABASE_URL: {{ .Values.plausible.databaseURL | toString | b64enc }}
  {{- end }}
  {{- if .Values.plausible.clickhouseDatabaseURL }}
  CLICKHOUSE_DATABASE_URL: {{ .Values.plausible.clickhouseDatabaseURL | toString | b64enc }}
  {{- end }}
  {{- if .Values.plausible.mailer.enabled }}
  {{- if eq .Values.plausible.mailer.adapter "Bamboo.Mua" }}
  {{- if .Values.plausible.mailer.smtp.password }}
  SMTP_USER_PWD: {{ .Values.plausible.mailer.smtp.password | toString | b64enc }}
  {{- end }}
  {{- end }}
  {{- if eq .Values.plausible.mailer.adapter "Bamboo.PostmarkAdapter" }}
  {{- if .Values.plausible.mailer.postmarkApiKey }}
  POSTMARK_API_KEY: {{ .Values.plausible.mailer.postmarkApiKey | toString | b64enc }}
  {{- end }}
  {{- end }}
  {{- if eq .Values.plausible.mailer.adapter "Bamboo.MailgunAdapter" }}
  {{- if .Values.plausible.mailer.mailgun.apiKey }}
  MAILGUN_API_KEY: {{ .Values.plausible.mailer.mailgun.apiKey | toString | b64enc }}
  {{- end }}
  {{- end }}
  {{- if eq .Values.plausible.mailer.adapter "Bamboo.MandrillAdapter" }}
  {{- if .Values.plausible.mailer.mandrillApiKey }}
  MANDRILL_API_KEY: {{ .Values.plausible.mailer.mandrillApiKey | toString | b64enc }}
  {{- end }}
  {{- end }}
  {{- if eq .Values.plausible.mailer.adapter "Bamboo.SendGridAdapter" }}
  {{- if .Values.plausible.mailer.sendgridApiKey }}
  SENDGRID_API_KEY: {{ .Values.plausible.mailer.sendgridApiKey | toString | b64enc }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- if .Values.plausible.extra_geolocation.enabled }}
  {{- if .Values.plausible.extra_geolocation.maxmind.licenseKey }}
  MAXMIND_LICENSE_KEY: {{ .Values.plausible.extra_geolocation.maxmind.licenseKey | toString | b64enc }}
  {{- end }}
  {{- end }}
  {{- if .Values.plausible.google.enabled }}
  {{- if .Values.plausible.google.clientID }}
  GOOGLE_CLIENT_ID: {{ .Values.plausible.google.clientID | toString | b64enc }}
  {{- end }}
  {{- if .Values.plausible.google.clientSecret }}
  GOOGLE_CLIENT_SECRET: {{ .Values.plausible.google.clientSecret | toString | b64enc }}
  {{- end }}
  {{- end }}
  {{- if .Values.plausible.databaseCA }}
  DATABASE_CA: {{ .Values.plausible.databaseCA | toString | b64enc }}
  {{- end }}
{{- end }}
