apiVersion: v1
kind: Pod
metadata:
  name: nvidia-test
  namespace: default
spec:
  runtimeClassName: nvidia
  containers:
 #- image: nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda12.5.0
  - image: nvidia/cuda:12.5.1-base-ubuntu22.04
    command:
    - "bash"
    - "-c"
    - "nvidia-smi; sleep 3600"
    imagePullPolicy: IfNotPresent
    name: nvidia-test
    resources:
      limits:
        nvidia.com/gpu: 1
      requests:
        memory: 1024Mi
  tolerations:
  - effect: NoSchedule
    key: kubezero-workergroup
    operator: Exists
