{{- if .Values.certManager.enabled }}
{{ template "kubezero.app" dict "root" . "name" "certManager" "type" "helm" }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  annotations:
    iam.amazonaws.com/permitted: ".*CertManagerRole.*"
{{- end }}
