{{- if .Values.forseti.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubezero-forseti
  name: forseti-metrics-service
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
  selector:
    app: kubezero-forseti
{{- end }}
