# nats
nats:
  enabled: false

  config:
    cluster:
      routeURLs:
        useFQDN: true

    jetstream:
      enabled: true
      fileStore:
        pvc:
          size: 10Gi
        maxSize: 8GB

  podTemplate:
    topologySpreadConstraints:
      kubernetes.io/hostname:
        maxSkew: 1
        whenUnsatisfiable: DoNotSchedule

  natsBox:
    enabled: false

  promExporter:
    enabled: false
    podMonitor:
      enabled: false

  mqtt:
    enabled: false

  istio:
    enabled: false
    # url: "mq.example.com"
    gateway: istio-ingress/private-ingressgateway

kafka:
  enabled: false

  cluster:
    name: example
    version: 4.1.1

  storage:
    size: 1Gi

  connect:
    enabled: false
    replicas: 1

akhq:
  enabled: false

  revisionHistoryLimit: 2

  configuration:
    akhq:
      connections:
        local:
          properties:
            bootstrap.servers: "example-kafka-plain-bootstrap:9092"

  istio:
    enabled: false
    url: example-akhq.local
    gateway: istio-ingress/private-ingressgateway


# rabbitmq
rabbitmq:
  enabled: false

  name: rabbitmq

  image:
    repository: public.ecr.aws/zero-downtime/zdt-rabbitmq
    tag: v4.2.8

  replicas: 1

  resources:
    requests:
      memory: 512Mi
      cpu: 100m
    limits:
      memory: 512Mi

  persistence:
    storage: 2Gi

  zoneSpread:
    enabled: false
    maxSkew: 1
    whenUnsatisfiable: DoNotSchedule    # ScheduleAnyway if you want soft spread

  pdb:
    enabled: false
    minAvailable: 2        # for 3 replicas: tolerate 1 down, keep quorum
    maxUnavailable: ""     # set one OR the other, not both

  additionalPlugins: []
  # - rabbitmq_delayed_message_exchange
  # - rabbitmq_shovel
  # - rabbitmq_shovel_management
  # - rabbitmq_federation
  # - rabbitmq_federation_management

  additionalConfig: |
    default_queue_type = quorum
#   disk_free_limit.relative = 1.5
#   cluster_partition_handling = pause_minority

  istio:
    url: "mq.example.com"
    enabled: false
    gateway: istio-ingress/private-ingressgateway
    amqp: false
    amqps: false
    mqtt: false
    mqtts: false

  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
