umami:
  enabled: false

  revisionHistoryLimit: 2

  # Disable sub-chart dep of bitnami postgres chart
  postgresql:
    enabled: false

  pg:
    auth:
      username: umami
      password: umami

    backup:
      enabled: false
      volumeSnapshotClassName: openebs-lvm-snapshots

  externalDatabase:
    type: postgresql

  database:
    databaseUrlKey: "databaseUrl"
    existingSecret: "umami-pg"

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
  # limits:
  #   cpu: 100m
  #   memory: 128Mi

  umami:
    appSecret:
      existingSecret: ""
      secret: "examplereallysecretstring"

    # -- Allows you to send metrics to a location different than the default `/api/send`. This is to help you avoid some ad-blockers.
    collectApiEndpoint: ""

    cloudMode: "1"
    disableBotCheck: "0"
    disableLogin: "1"
    enableTestConsole: "0"
    logQuery: "0"
    removeTrailingSlash: "0"
    removeDisableLoginEnv: false

  istio:
    enabled: false
    gateway: istio-ingress/private-ingressgateway
    url: umami.example.com
